on: [push]

jobs:
  packer-build-all:
    runs-on: ubuntu-latest
    name: A job building all images
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docker image
        run: docker build . -t raspberry-cluster-tool
      - name: Create output and cache directories
        run: |
              mkdir output
              mkdir cache
      - name: Run docker image
        run: |
              docker run --rm --privileged --cap-add=ALL -v /dev:/dev raspberry-cluster-tool \
                --mount type=bind,source="$PWD"/output,target=/app/output \
                " build all --enable-debug --enable-custom-output "
