on: [push]

jobs:
  packer-build-all:
    runs-on: ubuntu-latest
    name: A job building all images
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install qemu and dependencies
        run: | 
              sudo apt install -y qemu binfmt-support qemu-user-static
              sudo apt-get install -y qemu-utils qemu-efi-aarch64 qemu-system-arm
              sudo apt-get install -y gettext-base parted
      - name: Install packer
        run: |
              wget https://releases.hashicorp.com/packer/1.7.0/packer_1.7.0_linux_amd64.zip packer-builder-arm-git
              unzip packer_1.7.0_linux_amd64.zip
              sudo mv packer /usr/local/bin/
      - name: Install arm builder plugin
        run: |
              git clone https://github.com/SwampDragons/packer-builder-arm 
              cd packer-builder-arm-git
              go mod download
              go build
              cp packer-builder-arm ../packer-builder-arm
      - name: Run packer build
        run: ./packer.sh build all --enable-debug --enable-custom-output
